### ISSUE TITLE
The data labels and image names do not match

### ISSUE THREAD

**Issue by zhangqiqi1228** [PhamQuocHuy1101/Character-independent-font-identification#4]
Hi, thanks for your sharing. 

When I used your codes and data to train the model, I found out that the data labels in csv files and image names do not match for the lowercase English characters. 

The image names for lowercases have an extra "_1" suffix while the labels do not have it. Therefore, it occurred the "FileNotFoundError". 

For example: 

![image](https://github.com/PhamQuocHuy1101/Character-independent-font-identification/assets/104071310/daf86532-9caa-477e-83e5-550db0733ee2)

![image](https://github.com/PhamQuocHuy1101/Character-independent-font-identification/assets/104071310/568d591c-1149-4b2e-8441-6c34e06d32da)

Could you provide the right dataset or give me some suggestions to fix the bug? Thanks!

**Comment by PhamQuocHuy1101** [comment]
@zhangqiqi1228 
Sorry, for a long time I haven't worked on that project. The image dataset still be downloaded, you can create train/val/test.csv file by yourself, the root folder name is the label of font, image name follow structure `<char>_<font>_<subfont>.png`

Thanks.

**Comment by zhangqiqi1228** [comment]
> @zhangqiqi1228 Sorry, for a long time I haven't worked on that project. The image dataset still be downloaded, you can create train/val/test.csv file by yourself, the root folder name is the label of font, image name follow structure `<char>_<font>_<subfont>.png`
> 
> Thanks.

Thanks for your reply!

Do you still have the python script to create train/val/test.csv file? If yes, could you please upload it for a reference? Thanks!

**Comment by PhamQuocHuy1101** [comment]
Oh I miss all code, after I reset the OS, long time .. (^_^)

**Comment by zhangqiqi1228** [comment]
> 

No worries! Thanks for your reply~
